vich_uploader:
    db_driver: orm

    mappings:
        document_file:
            uri_prefix: /images/documents
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true